name: Build
on: push
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Make
        run: make build
        env:
          BUILD_SUFFIX: ${{ runner.os }}-${{ runner.arch }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/matticnote-*
